#!/bin/sh
#
#    <Script to control temperature of CPU>
#    Copyright (C) 2006  Laurent Guignard
#
#   This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

ACPI=`which acpi`
XMESS=`which xmessage`
ALERT_TEMP=70

TEMP=`$ACPI -t  | grep Bat  | awk '{ print $4 }' | awk -F% '{ print $1 }'`

if [[ $TEMP -gt $ALERT_TEMP ]]
then
	DISPLAY=:0.0 $XMESS -center "Température supérieure à $ALERT_TEMP : $TEMP" &
fi
