#!/usr/bin/perl
#
#    <Script to check logs>
#    Copyright (C) 2009  Laurent Guignard<lguignard.debian@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; version 2 of the License
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, 
#    MA 02110-1301 USA
#


my %apache_mounth=(
	"01"=>"Jan",
	"02"=>"Feb",
	"03"=>"Mar",
	"04"=>"Apr",
	"05"=>"May",
	"06"=>"Jun",
	"07"=>"Jul",
	"08"=>"Aug",
	"09"=>"Sep",
	"10"=>"Oct",
	"11"=>"Nov",
	"12"=>"dec"
	);



#
# Check iptables logs
my %iptables;


#
# Check Apache logs
#	\param $_[0] log file to analyse
#	\param $_[1] File on which HTTP request
sub apache_cnx_file {
	my $logfile=$_[0];
  my $file=$_[1];
	my @date; my @ip;

	print "$logfile - target :$file\n";

	open(HF,"grep \"$file\" \"$logfile\" |");
	while(<HF>) {
		my $line=$_;
		if($line=~/(.*)(\[.*\])(.*)/) { # Date
			push @date,$2;
		}
		if($line=~/(([0-9]{1,3}\.){3}[0-9]{1,3})(.*)/) { # IP address
			push @ip,$1;
		}
	}
	close HF;


# Display results
	for(my $i=1 ; $i-1<=$#date ;$i++) {
		print $i." - ".$date[$i-1]. " - ".$ip[$i-1]."\n";
	}
}


apache_cnx_file($ARGV[0],"todo.css");


