#!/bin/bash
#
#    <Script to add everything needed in pam configuration file to
#			use LDAP authentification>
#    Copyright (C) 2009  Laurent Guignard<lguignard.debian@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; version 2 of the License
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor Boston, 
#    MA 02110-1301 USA
#

PAM_PATH='/etc/pam.d'


for file in `find $PAM_PATH -name "common-*" -print`
do
	mv "$file" "$file.bak"
	echo "auth [success=1 default=ignore] pam_unix.so" >> "$file"
	echo "auth required pam_ldap.so use_first_pass" >> "$file"
	echo "auth required pam_permit.so" >> "$file"
	cat "$file.bak" >> "$file"
done







