#!/bin/sh
#
#    <Script to build and update pbuilder directory hierarchy>
#    Copyright (C) 2008  Laurent Guignard
#
#   This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; version 2 of the License
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	\todo This script has to be updated to suite needs
#		- get the distribution name from command line parameters
#		- 
#

# Create chroot environment with build-essential packages 
pbuilder create --debootstrapopts --variant=buildd

# Update 
pbuilder update --distribution DIST-NAME --override-config
