#!/bin/sh
#
#    <Script to add a secondary group to a user>
#    Copyright (C) 2006  Laurent Guignard
#
#   This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


usage() {
	echo "Usage $0 : "
	echo ""
	echo -e "\t $0 <acount name> <group to add>"
	echo
	echo -e "\tThis script adding a group to a user. It must be run with root account."
	echo -e "\tThe first argument is the account name."
	echo -e "\tThe second argument is a valid group name."
	echo -e "\tThis script only display errors or a log that describe the operation."
}




if [ $# -ne 2 ]; then
	usage
	exit 1
fi


USER=$1
NEW_GROUP=$2

#MAINGROUP=`groups $USER | awk '{ print $3 }'`

echo "Adding $NEW_GROUP to user $USER ..."

CMD="/usr/sbin/usermod -G `groups $USER | sed -e 's/ /,/g'`,$NEW_GROUP $USER"
$CMD


