.TH my-alert-bat 1 
.SH NAME
my-alert-bat \- laptop battery survey script
.SH SYNOPSIS
.B m-alert_bat
.br
.SH DESCRIPTION
This script is used to survey the laptop battery power charge.
It display a message when battery is fully charged and when the 
battery level is under the lower level accepted it shutdown 
the laptop.
.SH SEE ALSO
.BR acpi (1),
.BR xmessage (1)
.SH AUTHOR
my-alert-bat was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
