.TH my-acpi-info 1 
.SH NAME
my-acpi-info \- display all host ACPI information
.SH SYNOPSIS
.B my-acpi-info
.br
.SH DESCRIPTION
This script displays all ACPI information of host (battery state, processor 
temperature, power status,...)
.SH SEE ALSO
.BR acpi (1)
.SH AUTHOR
my-acpi-info was written by Laurent Guignard <lguignard.debian@fmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
