.TH my-alert-temp 1 
.SH NAME
my-alter-temp \- procesor temperature survey
.SH SYNOPSIS
.B my-alert-temp
.br
.SH DESCRIPTION
This script is used to survey the host processor temperature.
.PP
.SH SEE ALSO
.BR acpi (1),
.BR xmessage (1)
.SH AUTHOR
my-alert-temp was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gamil.com>,
for the Debian project (but may be used by others).
