.TH my-bugapt 1 
.SH NAME
my-bugapt \- script to display all registered bugs for package to upgrade
.SH SYNOPSIS
.B bugapt
.br
.SH DESCRIPTION
This display in console all registered bugs about all packages that need 
an upgrade after a debian package reference update (apt-get/aptitude update).
.SH SEE ALSO
.BR aptitude (1),
.BR apt-get (1),
.BR apt-listbugs (1)
.SH AUTHOR
my-bugapt was written by Laurent Guignard <lguignard.debian@gmail.com> after several reads
on Internet.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
