.TH my-capture 1
.SH NAME
capture \- Tool to create screen snapshot 
.SH SYNOPSIS
.B capture
.RI [ options ] " files" ...
.br
.SH DESCRIPTION
This script make screen snapshot at regular time until the CTR+c keys are 
pressed.
.B capture
and
.PP
.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.B \-h, \-\-help
Show summary of options.
.SH SEE ALSO
.BR scrot (1)
.SH AUTHOR
my-capture was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
