.TH my-conf-vpn 1 
.SH NAME
my-conf-vpn \- Configure OpenVPN
.SH SYNOPSIS
.B my-conf-vpn
"directory"
.br
.SH DESCRIPTION
This script is used to create an OpenVPN configuration file. All needed
information are asked to user.
.BR
.B directory 
Set the OpenVPN configuration file destination
.SH SEE ALSO
.BR openssl (1),
.BR openvpn (1)
.SH AUTHOR
my-conf-vpn was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
