.TH my-cyclo-epreuve 1 
.SH NAME
my-cyclo-epreuve \- Create a text file of "cyclosportives"
.SH SYNOPSIS
.B my-cyclo-epreuve
.SH DESCRIPTION
This script will create a file which contains all "cyclosportives" of
velo 101 web page.
.SH SEE ALSO
.BR wget (1)
.BR xsltproc (1)
.SH AUTHOR
my-cyclo-epreuve was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
