.TH my-count 1 
.SH NAME
my-count \- launch sloccount program on SIContact project sources in metro-gi user's home directory
.SH SYNOPSIS
.B my-count
.br
.SH DESCRIPTION
This script is project dedicated !
.PP
This script save sloccount output to /home/metro-gi/temp/sicontact_count/--hour--.txt file.
.PP
This script is used to manage SIContact project to evaluate the work done and give an 
idea of the work needed to reach the project's goal. It is a project's dedicated script.
.PP
.SH SEE ALSO
.BR sloccount (1)
.SH AUTHOR
my-count was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
