.TH my-dvd-slideshow 1
.SH NAME
my-dvd-slideshow-perso \- tool create a video slideshow from images
.SH SYNOPSIS
.B my-dvd-slideshow-perso
.RI " images_dir"  " duration" " dvd-slideshow_config_dest_file"
.PP
.SH DESCRIPTION
This script create a video Divx file from a directory which contains several 
image files (Jpeg).
.PP
.B images_dir :
This is the complete path to directory where are stored all images to transform into a video.
.PP
.B duration :
This is the duration between each image of the slideshow.
.PP
.B dvd-slideshow_config_dest_file :
This is the complete file name (complete path and file name) of the dvd-slideshow configuration file.
.PP
Show summary of options.
.SH SEE ALSO
.BR dvd-slideshow (1),
.BR convert (1),
.BR identify (1)
.SH AUTHOR
my-dvd-slideshow-perso was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
