.TH my-diff-dir 1 
.SH NAME
my-diff-dir \- check difference between files in two different directories
.SH SYNOPSIS
.B my-diff-dir " directory1" " directory2"
.br
.SH DESCRIPTION
This script is used to difference between files in two different directories.
.PP
The local repository of RFCs ($HOME/doc/rfcs) needs to exist. You have to
create the doc/rfcs directory under your home directory.
.PP
Difference between two directories is stored in $HOME/tmp/result.txt file and 
is displayed at screen.
.SH SEE ALSO
.BR md5sum (1)
.SH AUTHOR
my-diff-dir was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
