.TH my-debbug 1 
.SH NAME
my-debbug \- Ask the Bts all bugs for a specific mail address
.SH SYNOPSIS
.B my-debbug
.SH DESCRIPTION
This script will send a mail to the Debian Bug Tracking System to
ask the list of bugs for a maintainer (by his mail address).
.PP
.SH SEE ALSO
.BR mail (1)
.SH AUTHOR
my-debbug written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gamil.com>,
for the Debian project (but may be used by others).
