.TH my-dos2unix 1
.SH NAME
my-dos2unix \- Tool to transform DOS file text to UNIX file text
.SH SYNOPSIS
.B my-dos2unix
source_file
.RI " file"
.SH DESCRIPTION
This script transform DOS file text to UNIX file text by deleting all 
non-printable end-line characters.
.B dos2unix
.PP
.B sourcefile
Full path of DOS text file which to convert in UNIX text file format.
.SH SEE ALSO
.BR tr (1)
.SH AUTHOR
my-dos2unix was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
