.TH my-fit2gpx 1 
.SH NAME
my-fit2gpx \- script to transform FIT files to GPX files
.SH SYNOPSIS
.B my-fit2gpx
[file]
.SH DESCRIPTION
This script is used to transform Garmin FIT files to GPX file format.
.PP
.SH SEE ALSO
.BR fit2tcx (1),
.BR gpsbabel (1).
.SH AUTHOR
my-fit2gpx was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
