.TH my-free-video-rip 1 
.SH NAME
my-free-video-rip \- Rip the Free provider streaming
.SH SYNOPSIS
.B my-free-video-rip 
 channel file
.br
.SH DESCRIPTION
This script is used to rip any channel of the video streaming of Free Internet
Access Provider in France with only the channel name and the output file.
.PP
.B channel
channel name as nrj12, nt1 and so on
.PP
.B file
saving file name of the streaming rip
.SH SEE ALSO
.BR mencoder (1)
.SH AUTHOR
my-free-video-rip was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
