.TH my-getpkglist 1 
.SH NAME
my-getpkglist \- script to ...
.SH SYNOPSIS
.B my-getpkglist
[username]
.SH DESCRIPTION
This script is used to ...
.PP
.B ...
...
.PP
.B ...
.PP
.B ...
...
.PP
.SH SEE ALSO
.BR ssh (1),
.SH AUTHOR
my-getpkglist was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
