.TH my-graver-dvd 1 
.SH NAME
my-graver-dvd \- directory back on DVD
.SH SYNOPSIS
.B graver-dvd
	" volume_name" " directory_to_burn"
.br
.SH DESCRIPTION
This script aims at backup a directory on a DVD in one shell command.
.PP
.B volume_name
is the name wanted for the DVD
.PP
.B directory_to_burn 
is the source directory to backup on DVD
.SH SEE ALSO
.BR dvdrecord (1),
.BR growisofs (1),
.SH AUTHOR
my-graver-dvd was written by Laurent Guignard <lguignard.debian@gmail.com>
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
