.TH my-graver-cd 1 
.SH NAME
my-graver-cd \- directory back on CD
.SH SYNOPSIS
.B graver-cd
	" volume_name" " directory_to_burn"
.br
.SH DESCRIPTION
This script aims at backup a directory on a CD in one shell command.
.PP
.B volume_name
is the name wanted for the CD
.PP
.B directory_to_burn 
is the source directory to backup on CD
.SH SEE ALSO
.BR cdrecord (1),
.BR mkisofs (1)
.SH AUTHOR
my-graver-cd was written by Laurent Guignard <lguignard.debian@gmail.com>
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
