.TH my-ip 1 
.SH NAME
my-ip \- Display the output IP address
.SH SYNOPSIS
.B my-ip
.SH DESCRIPTION
This script will display the output IP address. This script use the 
http://checkip.dyndns.org/ site.
.PP
If script is not able to connect to dyndns.org, so "Off line" message 
is displayed.
.PP
A connection timeout is set to 
.B four 
seconds, and after this time.
.SH SEE ALSO
.BR wget (1)
.SH AUTHOR
my-ip was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
