.TH my-iso2utf8 1 
.SH NAME
my-iso2utf8 - ISO-8859-1 to UTF-8 convert script
.SH SYNOPSIS
.B iso2utf8
directory
.SH DESCRIPTION
This script is used to convert text file of a directory from ISO-8859-1 
encoding characters to UTF-8 encoding.
.RS
.B directory 
This is the directory in which text files are. 
.RE
.PP
.B Be careful, only text files have to be in the directory passed as argument.
.SH SEE ALSO
.BR iconv (1)
.SH AUTHOR
my-iso2utf8 was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
