.TH my-ip-net-calculator 1 
.SH NAME
my-ip-net-calculator \- determine the network from an address and a netmask
.SH SYNOPSIS
.B my-ip-net-calculator
.SH DESCRIPTION
This script aims at determine the network from an IP address and a netmask.
.PP
.SH SEE ALSO
.BR ip_net_calculator (1)
.SH AUTHOR
my-ip-net-calculator was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
