.TH my-kvm.cf 1
.SH NAME
/etc/defeault/my-kvm.cf \- configuration file of my-kvm script
.br
.SH DESCRIPTION
This is the configuration file of my-kvm script.
.PP
Futher informat have to be filled here...
Just see the configuration, then you could filled this man page and
help the OpenSource movement.
.SH SEE ALSO
.BR my-kvm (1)
.BR kvm (1)
.SH AUTHOR
The my-kvm suite was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
