.TH my-linecount 1 
.SH NAME
my-linecount \- count number of lines in a lot of file
.SH SYNOPSIS
.B my-linecount
.br
	directory files extension
.SH DESCRIPTION
It aims at count the number of line all file of a directory.
.P
.B directory 
This is the directory in which text files are
.P
.B files extension
This is the extension of file under SHELL form (*.h, *.c, *.txt, ...)
.PP
.SH SEE ALSO
.BR wc (1)
.SH AUTHOR
linecount was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
