.TH my-mkcdaudio 1 
.SH NAME
my-mkcdaudio \- create an audio CD from wav files
.SH SYNOPSIS
.B mkcdaudio 
directory
.br
.SH DESCRIPTION
This script is used to create an audio CD from a directory which contains 
only WAV encoded files.
.RS
.B directory
This is the directory where to find all WAV encoded files which are to be 
burn on CD.
.RE
.SH SEE ALSO
.BR cdrecord (1)
.SH AUTHOR
mkcdaudio was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
