.TH my-mp32wav 1
.SH NAME
my-mp32wav \- tool to convert file from MP3 to WAV
.SH SYNOPSIS
.B my-mp32wav
.RI [file] 
.RI [directory] 
.br
.SH DESCRIPTION
This script converts all files of directory or the file provided as argument 
from MPEG3 to WAV encoding format.
.PP
.B Caution : all files contained in the directory provided as argument had to be 
.B audio (MP3) files. There is no test on file type which will be computed.
.PP
Show summary of options.
.SH SEE ALSO
.BR mp123 (1),
.BR sox (1)
.SH AUTHOR
my-mp32wav was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
