.TH my-mix-aud-vid 1 
.SH NAME
my-mix-aud-vid \- mix audio and video files from the mk_dv script of this package
.SH SYNOPSIS
.B diff-dir file
.br
.SH DESCRIPTION
This script is used mix sound and video extract by the mk_dv script of this 
package. It uses mplex software.
.P
.B file
This is the file name without any extension provided by mk_dv script (in this package).
.PP
This script creates an Mpeg file with the two audio an video file from mk_dv script.
.SH SEE ALSO
.BR plex (1)
.SH AUTHOR
my-mix-aud-vid  was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
