.TH my-mess 1 
.SH NAME
my-mess \- display a message in X11 environnement
.SH SYNOPSIS
.B my-mess
.SH DESCRIPTION
This script will display the $MESSAGE environnement variable in an X11 box.
.SH SEE ALSO
.BR xmessage (1)
.SH AUTHOR
my-mess was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
