.TH my-md5 1 
.SH NAME
my-md5 \- script to ...
.SH SYNOPSIS
.B my-md5
...
.SH DESCRIPTION
This script is used to ...
.PP
.B ...
...
.PP
.B ...
.PP
.B ...
...
.PP
.SH SEE ALSO
.BR ssh (1),
.SH AUTHOR
my-md5 was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
