.TH my-mk-dv 1
.SH NAME
my-mk-dv \- Tool to encode Divx files into DV
.SH SYNOPSIS
.B my-mk-dv 
.RI [ options ] directory
.br
.SH DESCRIPTION
This script encodes all files of the directory passed as argument into 
a Divx file at DV encoding format and store then into the argument/target 
directory.
.PP
.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.RS
.B \-h, \-\-help
Show summary of options.
.RE
.SH SEE ALSO
.BR ffmpeg (1)
.SH AUTHOR
mk_dv was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
