.TH my-nef2jpg 1 
.SH NAME
my-photo \- script to convert NEF photos to JPG
.SH SYNOPSIS
.B my-nef2jpg
directory
.SH DESCRIPTION
This script is used to convert NEF photo (NIKON) to JPG file.
.PP
.B directory
source directory in which all photos to convert are saved.
.SH SEE ALSO
.BR ufraw-batch (1)
.SH AUTHOR
my-nef2jpg was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
