.TH my-nef2jpg 1 
.SH NAME
my-photo \- script to convert NEF photos to JPG
.SH SYNOPSIS
.B my-nef2jpg 
	directory
.SH DESCRIPTION
This script is used to convert NEF file (NIKON photo) to JPG file.
.PP
.B directory
directory where are saved all NEF files to convert into JPEG format. 
This argument could be build with system shell jokers like '*' or '?' 
characters (this option hasn't been tested).
All JPEG files are stored in 'directory/jpeg' directory. 'jpeg' directory 
is automatically created if it doesn't exist.
.SH SEE ALSO
.BR ufraw-batch (1)
.SH AUTHOR
my-nef2jpg was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
