.TH my-ntp 1
.SH NAME
my-ntp \- tool to synchronize host time with a list of NTP servers
.SH SYNOPSIS
.B my-ntp
.RI server1
.RI server2
.RI ...
.SH DESCRIPTION
This script will synchronize the host date and time with the first 
time server within the list provided as argument that answer.
.BR my-ntp (1),
.BR ntpdate (1)
.SH AUTHOR
my-ntp was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
