.TH my-powertop 1 
.SH NAME
my-powertop \- tool to configure system to use less power
.SH SYNOPSIS
.B my-powertop
.br
.SH DESCRIPTION
This script is used to configure host to use less power as possible.
.PP
This script come from the powertop recommandations and need to be 
upgrade with kernel features adds and updates.
.PP
.SH AUTHOR
my-powertop was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
