.TH my-photo 1 
.SH NAME
my-photo \- script to sort photos according to their date
.SH SYNOPSIS
.B my-photo
source dest
.SH DESCRIPTION
This script is used to sort photos into directories according to their date.
.PP
.B source
source directory in which all photos to sort are saved.
.PP
.B dest
destination directory in which photos will be moved and sorted.
.SH SEE ALSO
.BR exiv2 (1)
.SH AUTHOR
my-photo was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
