.TH my-rename-file 1 
.SH NAME
my-rename-file \- replace string into file name
.SH SYNOPSIS
.B my-rename-file 
string_to_search replacing_string directory
.br
.SH DESCRIPTION
This script aims at rename files from a directory. It search a special string 
(string_to search parameter) in all files name and replace by another string 
(replacing_string parameter).
.SH SEE ALSO
.BR sed (1)
.SH AUTHOR
rename_file was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
