.TH my-rip 1 
.SH NAME
my-rip \- Rip an MP3 stream whit streamripper
.SH SYNOPSIS
.B rip 
	url
.br
.SH DESCRIPTION
This script save the current stream on the 
.P
.B "url"
parameter and save it into your $HOME/tmp directory
.PP
.SH SEE ALSO
.BR streamripper (1)
.SH AUTHOR
my-rip was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
