.TH my-rip-orange 1 
.SH NAME
my-rip-orange \- Rip the TV stream from Orange FAI
.SH SYNOPSIS
.B my-rip-orange
	url
.br
.SH DESCRIPTION
.B This script doesn't work. It need more work !!!
.B If you have solution you can mail me and i'll package it.
This script save the current stream on the hard disk.
.P
.B url
parameter and save it into your $HOME/tmp directory
.PP
This script is just under building, so if you have already a solution,
 you are welcome to share it.
.SH SEE ALSO
.BR ???
.SH AUTHOR
my-rip-orange is written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
