.TH my-saveldap 1 
.SH NAME
my-saveldap \- Save my ldap directory
.SH SYNOPSIS
.B my-saveldap
.br
.SH DESCRIPTION
This script save the LDAP directory. It is a basic script that need 
to be improved.
.PP
.SH SEE ALSO
.BR ldapsearch (1)
.SH AUTHOR
my-saveldap was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
