.TH my-ssl-ca 1 
.SH NAME
my-ssl-ca \- create a new OpenSSL infrastructure
.SH SYNOPSIS
.B my-ssl-ca
.br
.SH DESCRIPTION
This script is used to create Openssl configuration and save this one into a new
directory hierarchy.
.SH SEE ALSO
.BR openssl (1)
.SH AUTHOR
my-ssl-ca was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
