.TH my-spamupdate 1 
.SH NAME
my-spamupdate \- script to update personal SPAM database
.SH SYNOPSIS
.B my-spamupdate
.br
.SH DESCRIPTION
This script will update SPAM database with selected SPAM mail. All SPAM mail
have to be placed in $HOME/Mail2009/.spam/ directory. This directory has to 
be under maildir format (contain cur,new and tmp subdirecties).
This script will update database for 2 tools : bogofilter and spamassassin.
.PP
.B This script need to be improve to be declared operational !
.PP
.SH SEE ALSO
.BR htc (1)
.SH AUTHOR
my-myspamupdate was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
