.TH my-stats-hist 1 
.SH NAME
my-stats-hist \- browser history and make statistics
.SH SYNOPSIS
.B history | stats_hist
.br
.SH DESCRIPTION
This script will show the most used shell commands.
.PP
.SH SEE ALSO
.BR history (1),
.BR awk (1),
.BR sort (1), 
.BR head (1)
.SH AUTHOR
my-stats-hist was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
