.TH my-stava.pl 1
.SH NAME
my-strava.pl \- tool to get strava activities
.SH SYNOPSIS
.B my-strava.pl
.SH DESCRIPTION
This script will get all activities for a specified client and token. 
These parameters can be set directly in PERL script.
.BR my-strava.pl (1),
.SH AUTHOR
my-strava.pl was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
