.TH my-search-str 1 
.SH NAME
my-search-str \- search a string in all file of a directory
.SH SYNOPSIS
.B search_str " directory" " string"
.SH DESCRIPTION
This script is used to search a specify string (argument number 2) into all files 
of a directory (argument number 1).
.PP
.RS
.B directory 
    directory in which all text files are
.B string
    string to search in all text files contained by the directory argument
.RE
.SH SEE ALSO
.BR find (1),
.BR grep (1)
.SH AUTHOR
my-search-str was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
