.TH my-time-prj 1
.SH NAME
my-time-prj \- tools to register time spent on project
.SH SYNOPSIS
.B my-time-prj
.RI project_name  [start|pause|clear]
.br
.SH DESCRIPTION
This script is done to register time spent on various projects and aims to be 
wmwork software compliant.
.PP
.RS
.B project_name
  To be fully wmwork compliant, the project name has to be in upper case and hasn't 
  exceed 4 characters.
.P
.B start|pause|clear
  This parameter is to command the script to start time count, make au pause or 
  clear the time spent on project.
.RE
.PP
.SH SEE ALSO
.BR wmwork (1)
.br
.SH AUTHOR
my-time-prj was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
