.TH my-tunnel 1 
.SH NAME
my-tunnel \- create a TCP tunnel throw the 8080 port
.SH SYNOPSIS
.B my-tunnel 
.br
.SH DESCRIPTION
This script will create a tunnel throw the 8080 port (usually used by proxies
hosts). This tunnel could be with an external host that is used as a relay. This
script is as much an example as a real script but it could be used to bypass a
proxy.
.PP
.B Becareful, in some cases, bypass a proxy could be assimilated as a "grave
fault" in your job and could cause fireout. You are the only responsible about
using this and what you do with.
.PP
.SH SEE ALSO
.BR htc (1)
.SH AUTHOR
my-tunnel was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
