.TH my-vidcut 1
.SH NAME
my-ntp \- tool to cut video
.SH SYNOPSIS
.B my-vidcut start end filename
.RI start
.RI end
.RI filename
.SH DESCRIPTION
This script will cut a video from start to end time.
filename argument is the source video file to cut.
.BR my-vidcut (1),
.SH AUTHOR
my-vidcut was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
