.TH my-wifi 1 
.SH NAME
my-wifi \- WIFI network configuration
.SH SYNOPSIS
.B my-wifi 
.SH DESCRIPTION
This script is used to configure he laptop WIFI network. It scans all available
networks and try to connect the selected one.
.PP
After a successful connection to a network you can save all information about in
a file and replay after a reboot or anything else needed a network
reconfiguration.
.PP
.RS
.B This script needs to be adapted because of the packaging requirements. This
.B will be done later.
.RE
.SH SEE ALSO
.BR iwconfig (1),
.BR iwlist (1),
.BR dhclient (1).
.SH AUTHOR
my-wifi was written by Laurent Guignard <lguignard.debian@gmail.com>.
.PP
This manual page was written by Laurent Guignard <lguignard.debian@gmail.com>,
for the Debian project (but may be used by others).
